spring.datasource.url=jdbc:postgresql://localhost:5432/mada
spring.datasource.username=mada
spring.datasource.password=mada
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.validator.apply_to_ddl=false
#spring.modulith.runtime.flyway-enabled=true
#spring.flyway.enabled=true
#spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
